---
- name: Test connectivity to Windows host
  hosts: 192.168.28.54
  gather_facts: no
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
  tasks:
    - name: Ping the Windows server
      win_ping: