---
- name: Detailed server status report
  hosts: 192.168.28.54
  gather_facts: no
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    
  tasks:
    - name: Ping the server to check if it's online
      ansible.windows.win_ping:
      register: ping_status
      ignore_errors: yes

    - name: Get CPU temperature from OpenHardwareMonitor via PowerShell
      ansible.windows.win_shell: |
        try {
            $tempSensor = Get-WmiObject -Namespace root\OpenHardwareMonitor -Class Sensor | Where-Object {$_.SensorType -eq 'Temperature' -and $_.Name -like "*CPU*"} | Select-Object Value
            if ($tempSensor) {
                Write-Output "$($tempSensor.Value) °C"
            } else {
                Write-Output "CPU temp sensor not found."
            }
        } catch {
            Write-Output "OpenHardwareMonitor provider not running or not found."
        }
      register: cpu_temp_output
      
    - name: Get server runtime
      ansible.windows.win_shell: |
        $os = Get-CimInstance Win32_OperatingSystem
        $lastBootUpTime = $os.LastBootUpTime
        $currentTime = Get-Date
        $upTime = $currentTime - $lastBootUpTime
        $days = $upTime.Days
        $hours = $upTime.Hours
        $minutes = $upTime.Minutes
        Write-Output "Uptime: $days days, $hours hours, $minutes minutes"
      register: uptime

    - name: Get detailed disk space
      ansible.windows.win_shell: |
        $disks = Get-CimInstance Win32_LogicalDisk | Where-Object { $_.DriveType -eq 3 }
        $diskInfo = @()
        foreach ($disk in $disks) {
          $freeGB = [math]::Round($disk.FreeSpace / 1GB, 2)
          $totalGB = [math]::Round($disk.Size / 1GB, 2)
          $usedGB = [math]::Round($totalGB - $freeGB, 2)
          $percentageUsed = [math]::Round(($usedGB / $totalGB) * 100, 2)
          $diskInfo += "Drive $($disk.DeviceID) - Used: $($usedGB) GB / Total: $($totalGB) GB ($($percentageUsed)%)"
        }
        Write-Output ($diskInfo -join "`n")
      register: disk_space

    - name: Display final report
      ansible.builtin.debug:
        msg: |
          ==================================================
          Server Status Report for {{ inventory_hostname }}
          ==================================================
          
          Online Status: {{ 'Online' if not ping_status.failed else 'Offline' }}

          --------------------------------------------------
          System Information
          --------------------------------------------------
          {{ uptime.stdout }}
          CPU Temperature: {{ cpu_temp_output.stdout }}

          --------------------------------------------------
          Disk Space
          --------------------------------------------------
          {{ disk_space.stdout }}